version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec puma -b 'tcp://0.0.0.0:3000'
    volumes:
      - .:/vendor
    ports:
      - "3000:3000"
    depends_on:
      - db
