require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ThoughtsController do

  # This should return the minimal set of attributes required to create a valid
  # Thought. As you add validations to Thought, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    return {:thought => "This is a thought."}
  end
  
  class ThoughtsController
    def authenticate_user!

    end
  end

  describe "GET index" do
    it "assigns all thoughts as @thoughts" do
      thought = Thought.create! valid_attributes
      get :index
      assigns(:thoughts).should eq([thought])
    end
  end

  describe "GET show" do
    it "assigns the requested thought as @thought" do
      thought = Thought.create! valid_attributes
      get :show, :id => thought.id.to_s
      assigns(:thought).should eq(thought)
    end
  end

  describe "GET new" do
    it "assigns a new thought as @thought" do
      get :new
      assigns(:thought).should be_a_new(Thought)
    end
  end

  describe "GET edit" do
    it "assigns the requested thought as @thought" do
      thought = Thought.create! valid_attributes
      get :edit, :id => thought.id.to_s
      assigns(:thought).should eq(thought)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Thought" do
        expect {
          post :create, :thought => valid_attributes
        }.to change(Thought, :count).by(1)
      end

      it "assigns a newly created thought as @thought" do
        post :create, :thought => valid_attributes
        assigns(:thought).should be_a(Thought)
        assigns(:thought).should be_persisted
      end

      it "redirects to the created thought" do
        post :create, :thought => valid_attributes
        response.should redirect_to(Thought.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved thought as @thought" do
        # Trigger the behavior that occurs when invalid params are submitted
        Thought.any_instance.stub(:save).and_return(false)
        post :create, :thought => {}
        assigns(:thought).should be_a_new(Thought)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Thought.any_instance.stub(:save).and_return(false)
        post :create, :thought => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested thought" do
        thought = Thought.create! valid_attributes
        # Assuming there are no other thoughts in the database, this
        # specifies that the Thought created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Thought.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => thought.id, :thought => {'these' => 'params'}
      end

      it "assigns the requested thought as @thought" do
        thought = Thought.create! valid_attributes
        put :update, :id => thought.id, :thought => valid_attributes
        assigns(:thought).should eq(thought)
      end

      it "redirects to the thought" do
        thought = Thought.create! valid_attributes
        put :update, :id => thought.id, :thought => valid_attributes
        response.should redirect_to(thought)
      end
    end

    describe "with invalid params" do
      it "assigns the thought as @thought" do
        thought = Thought.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Thought.any_instance.stub(:save).and_return(false)
        put :update, :id => thought.id.to_s, :thought => {}
        assigns(:thought).should eq(thought)
      end

      it "re-renders the 'edit' template" do
        thought = Thought.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Thought.any_instance.stub(:save).and_return(false)
        put :update, :id => thought.id.to_s, :thought => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested thought" do
      thought = Thought.create! valid_attributes
      expect {
        delete :destroy, :id => thought.id.to_s
      }.to change(Thought, :count).by(-1)
    end

    it "redirects to the thoughts list" do
      thought = Thought.create! valid_attributes
      delete :destroy, :id => thought.id.to_s
      response.should redirect_to(thoughts_url)
    end
  end
end

